"""
Emit shell commands for a grid of train.py runs from a JSON manifest (no execution).

Example:
  python scripts/render_train_sweep.py --matrix configs/train_sweep.example.json > outputs/train_sweep_plan.sh
"""
import argparse
import json
from pathlib import Path


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--matrix", required=True, help="JSON file: list of objects passed as train.py CLI flags.")
    p.add_argument("--shebang", default="#!/usr/bin/env bash", help="First line of generated script.")
    p.add_argument("--set_e", action="store_true", help="Emit 'set -euo pipefail' after shebang.")
    args = p.parse_args()

    raw = json.loads(Path(args.matrix).read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise SystemExit("Matrix JSON must be a list of job objects.")

    lines = [args.shebang]
    if args.set_e:
        lines.append("set -euo pipefail")
    lines.append("# Generated by render_train_sweep.py — review before running.")
    lines.append("")

    for raw_job in raw:
        if not isinstance(raw_job, dict):
            raise SystemExit("Each matrix entry must be a JSON object.")
        job = dict(raw_job)
        name = job.pop("name", None)
        if name and "output_dir" not in job:
            job["output_dir"] = f"outputs/train_sweep/{name}"

        parts = ["python", "scripts/train.py"]
        for k, v in sorted(job.items()):
            if v is None:
                continue
            flag = f"--{k}"
            if isinstance(v, bool):
                if v:
                    parts.append(flag)
            else:
                parts.append(flag)
                parts.append(str(v))
        lines.append(" ".join(parts))
        lines.append("")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
